from typing import Dict, List, Optional, Protocol


class EmailsInterface(Protocol):
    def insert_email(self, email: Dict) -> None: ...
    def get_last_n_emails(self, n: int) -> List[Dict]: ...
    def get_email_by_id(self, email_id: str) -> Optional[Dict]: ...
